OANDA_API_KEY = ""
OANDA_ACCOUNT_ID = ""

OPENAI_API_KEY = ""
OPENAI_MODEL = ""

AWS_ACCESS_KEY_ID = "AKIAXXG5C4Y3L5EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
AWS_REGION = ""
NOTIFICATION_PHONE_NUMBER = "+19876543210"

TRADELOCKER_BASE_API_URL = ""
TRADELOCKER_EMAIL = ""
TRADELOCKER_PASSWORD = ""
TRADELOCKER_SERVER = ""
ROUNDTRIP_COMMISSION_PER_LOT = 0.0
DOLLARS_PER_PIP_PER_LOT = 0.0