OANDA_API_KEY = ""
OANDA_ACCOUNT_ID = ""

OPENAI_API_KEY = ""
OPENAI_MODEL = ""

AWS_ACCESS_KEY_ID = "AKIAXXG5C4Y3L5EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
AWS_REGION = ""

TRADELOCKER_BASE_API_URL = ""
TRADELOCKER_EMAIL = ""
TRADELOCKER_PASSWORD = ""
TRADELOCKER_SERVER = ""
COMMISSION_PER_LOT = 0.0